applicatie/__init__.py
import os
from flask import Flask


def create_app(config=None):
    app = Flask(__name__, instance_relative_config=True)

    if config is None:
        # read config file from the instance folder
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load config object passed on start-up
        app.config.from_object(config)

    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from applicatie.main import bp as main_bp
    app.register_blueprint(main_bp)

    print("Running with configuration = {!s}".format(app.config))
    # print('Running with configuration: ' + app.config['APP_ENV'])
    return app

applicatie/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from applicatie.main import routes

applicatie/main/routes.py
import io
import json
import sys
import logging

from flask import render_template, request, current_app

from applicatie.main.custom_exceptions import OSFAanroepError
from applicatie.main import bp
from applicatie.main.verwerking import Verwerking
from config.configurations import EXTERNE_CONTROLE, VERSIE
from applicatie.logic.foutmeldingen import geef_gebruikersvriendelijke_foutmeldingen


_logger = logging.getLogger(__file__)


@bp.route("/", methods=['GET', 'POST'])
def index():
    """
    Hoofdpagina. We controleren het type van de browser en of er een bestand is geselecteerd.
    Ook is hier de logica ondergebracht voor het verwerken van een mutatie zodat deze zichtbaar wordt
    door het verversen van het scherm.
    """

    # javascript debug status
    js_debug_status = (current_app.config['ENV'] == 'debugjavascript')

    if request.method == 'POST':
        reqform = request.form.to_dict()
        if (not request.files.get('file')) and 'data' in reqform:
            # Mutatie verwerken
            mutatie = reqform

            data = json.loads(mutatie.pop('data'))
            bestandsnaam = mutatie.pop('bestandsnaam')
            uploaded_file = io.BytesIO(json.dumps(data).encode('utf-8'))
            return matrix(uploaded_file, mutatie)

        elif not request.files.get('file'):
            foutmeldingen = ['Geen json bestand geselecteerd']
            return geef_index_met_foutmeldingen(foutmeldingen, js_debug_status)

        else:
            browsertype = request.user_agent.browser
            if browsertype not in ['firefox', 'chrome']:
                foutmeldingen = ['Deze website werkt alleen met Firefox en Chrome browsers']
                return geef_index_met_foutmeldingen(foutmeldingen, js_debug_status)
            uploaded_file = request.files['file']
            bestandsnaam = uploaded_file.filename

            if EXTERNE_CONTROLE and bestandsnaam != '':
                uploaded_file.save(bestandsnaam)

            return matrix(uploaded_file)

    elif request.method == 'GET':
        foutmeldingen = []
        browsertype = request.user_agent.browser
        if browsertype not in ['firefox', 'chrome']:
            foutmeldingen = ['Deze website werkt alleen met Firefox en Chrome browsers']
        return geef_index_met_foutmeldingen(foutmeldingen, js_debug_status)


def geef_tabnaam(waarde_kant):
    """
    Automatisch open bijbehorende tab.
    """
    if waarde_kant == 'lasten':
        tabnaam = 'LastenLR'
    elif waarde_kant == 'baten':
        tabnaam = 'BatenLR'
    elif waarde_kant == 'balans_lasten':
        tabnaam = 'LastenBM'
    elif waarde_kant == 'balans_baten':
        tabnaam = 'BatenBM'
    elif waarde_kant == 'balans_standen':
        tabnaam = 'Balans'
    elif waarde_kant == 'kengetallen':
        tabnaam = 'Kengetallen'
    elif waarde_kant == 'beleidsindicatoren':
        tabnaam = 'Beleidsindicatoren'
    elif waarde_kant == 'bulkcorrecties':
        tabnaam = 'Bulk_correcties'
    else:
        # Foutafhandeling
        print('Fout: Onbekende waarde_kant', waarde_kant)
        tabnaam = None
    return tabnaam


# opmerking: we staan alleen de POST-methode toe, anders krijg je een fout.
@bp.route("/matrix", methods=['POST'])
def matrix(jsonbestand, mutatie=None):
    """
    Haal het JSON-bestand op en geef evt. foutmeldingen terug.
    Indien geen fouten, laad de pagina met een overzicht van de data.
    """
    # javascript debug status
    js_debug_status = (current_app.config['ENV'] == 'debugjavascript')

    try:
        verwerking = Verwerking(jsonbestand)
    except OSFAanroepError:
        foutmeldingen = ['Er is een fout opgetreden bij de controle van het bestand,'
                         ' probeert u het opnieuw of contacteer team Overheidsfinancien.']
        return geef_index_met_foutmeldingen(foutmeldingen, js_debug_status)

    foutmeldingen = []
    if verwerking.controle_fouten:
        # Fouten geconstateerd door OSF.
        foutmeldingen = geef_gebruikersvriendelijke_foutmeldingen(verwerking.controle_fouten,
                                                                  verwerking.fouten_overzicht)
    if verwerking.fouten:
        # Fouten geconstateerd door onszelf toevoegen.
        foutmeldingen.extend(verwerking.fouten)
    if foutmeldingen:
        return geef_index_met_foutmeldingen(foutmeldingen, js_debug_status)

    if mutatie and not verwerking.fouten:
        waarde_kant = mutatie.pop('waarde_kant')
        tabnaam = geef_tabnaam(waarde_kant)

        if not waarde_kant == 'bulkcorrecties':
            # verwerken van een enkele correctie
            try:
                if '.' in mutatie['bedrag']:
                    bedrag = float(mutatie['bedrag'])
                else:
                    bedrag = int(mutatie['bedrag'])
            except ValueError:
                print(f"Fout: bedrag is geen numerieke waarde {mutatie['bedrag']})", file=sys.stderr)
                bedrag = 0

            mutatie['bedrag'] = bedrag
            # omschrijving toevoegen aan het 'details' element
            mutatie['details'] = {"omschrijving": "Mutatie toegevoegd met Ocido."}
            verwerking.muteer(waarde_kant, mutatie)

        else:
            # verwerken van bulkcorrecties
            bulkcorrecties = json.loads(mutatie['bulkcorrecties'])
            for correctie in bulkcorrecties.values():
                for key, corr in correctie.items():
                    verwerking.muteer(key, corr)

    else:
        tabnaam = None

    verwerking.run()

    if verwerking.fouten:
        return geef_index_met_foutmeldingen(verwerking.fouten, js_debug_status)

    # Render sjabloon
    params = {
        'bestandsnaam': jsonbestand.filename,
        'tabnaam': tabnaam,
        'data': verwerking.data_bestand,
        'sjabloon': verwerking.sjabloon_meta,
        'draaitabellen': verwerking.draaitabellen,
        'controle_resultaten': verwerking.controle_resultaten,
        'meta': verwerking.metadata,
        'contact': verwerking.contact,
        'debug_status': js_debug_status,

        # hebben we onderstaande nog nodig?
        'errormessage': "",
    }

    return render_template("matrix.html", **params)


def geef_index_met_foutmeldingen(foutmeldingen, js_debug_status):
    return render_template("index.html", errormessages=foutmeldingen, debug_status=js_debug_status, versienummer=VERSIE)

applicatie/templates/index.html
{% extends "layout.html" %}

{% block content %}

	<form class="form form-horizontal margin-medium" enctype="multipart/form-data" method="post">
		<div class="col-sm-12">
			<br>
				<center>
					<h1>OCIDO</h1>
					<h2>Online Controle Iv3 Decentrale Overheden {{versienummer}}</h2>
					<h4>Dit hulpmiddel is bedoeld voor controle en inzending van iv3 data door overheidsinstanties.</h4>
					<br/>

					<div class="input-group col-sm-4 center-block">
    					<label class="input-group-btn">
							<span class="btn btn-primary btn-block">
            				Kies een JSON-bestand&hellip;
							<input id="file" accept=".json" name="file" type="file" style="display:none;"
								   onchange="$('#upload-file-info').val($(this).val().split('\\').pop());
								   				$('div#error_messages').empty();">
							</span>
						</label>
						<input type="text" class="form-control text-center" id="upload-file-info" readonly>
					</div>

					<div style="clear:both;height:2em;"></div>

					<div class="input-group col-sm-4 center-block">
					   <button class="btn btn-primary btn-block">
						   Start controle van het gekozen JSON-bestand
					   </button>
					</div>

                    <br/>

					<div id="error_messages">
                    {% for errormessage in errormessages %}
						<div class="error">{{ errormessage }}</div>
                    {% endfor %}
					</div>

					<!--
                    <div>
						<input type="text" value="8" name="mytextbox" size="1"/>
						<input type="submit" class="btn" value="Selecteer een JSON bestand" name="HaalBestandOp" value="okido">
						<a href="{{url_for('main.matrix')}}" class="btn-secundary">matrices</a>
					</div>
                    -->
				</center>
			</br>
		</div>
	</form>
{% endblock %}

<!--
</html>
-->

applicatie/templates/layout.html
{% from 'macros.html' import set_javascript_debug_status %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- <link href="{{url_for('static', filename='css/main.css') }}" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" >
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" >
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/pivot.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/pivot_extra.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/cbs-style.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/ctiv.css') }}" >
    <meta charset="utf-8">
    <title>Check iv3</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <script src="https://d3js.org/d3.v5.min.js"></script> -->

    <!-- External libs -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/jquery-ui.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/d3.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/jquery.ui.touch-punch.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/papaparse.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/chosen.jquery.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/plotly-basic-latest.min.js') }}"></script>
    <!-- <script type="text/javascript" src="jquery-3.3.1.min.js"></script> -->

    <!-- Pivot table -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/pivot.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/d3_renderers.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/plotly_renderers.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/extern/export_renderers.js') }}"></script>

    <!-- Custom -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/custom/matrix.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/custom/bulk.js') }}"></script>


</head>
<!--body class="body" style="background-color: #00A1CD"-->
<body class="body" style="background-color: #E4E1DD ">
    <div class="container-fluid" style="min-height:95%; ">
        <div class ="row">
            <div class="col-sm-12">
                <br>
                <center>
                    <div style="clear: both">
                         <img src="{{url_for('static', filename='images/cbs-brand.svg')}}"
                            alt="cbs logo" height="64" width="50" style="float: left">
                        <h1 style="float: center"> Centraal Bureau voor de Statistiek </h1>
                    </div>
                </center>
            </div>
        </div>
    </div>

    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

{{ set_javascript_debug_status(debug_status) }}

applicatie/templates/macros.html
{% macro set_javascript_debug_status(debug_status) %}

{% set javascript_debug_status = (debug_status|string).lower() %}
<script>
    // zet javascript const DEBUG_STATUS
    const DEBUG_STATUS = ("{{ javascript_debug_status }}" === "true");
</script>

{% endmacro %}


{% macro draaitabel(tabel) %}

<!-- Tab content -->
<div class="container">
    <!-- TODO Je kunt spelen met class=table of table-striped -->
    <!-- https://getbootstrap.com/docs/3.3/css/#tables-example -->
    <table border="1" class="table pvtTable draaitabel" style="opacity: 1"
           naam='{{ tabel.naam }}'
           rij_naam='{{ tabel.rij_naam }}'
           kolom_naam='{{ tabel.kolom_naam }}'
           data='{{ tabel.data | tojson }}'
           detail_kolommen='{{ tabel.geef_detail_kolommen() | tojson }}'
           contenteditable={{ tabel.is_bewerkbaar }}
    >
        <thead>
        <tr>
            <th colspan="1" rowspan="1"></th>
            <th class="pvtAxisLabel">{{ tabel.kolom_naam.title() }}</th>

            {% for kolom in tabel.kolommen %}
            <th class="pvtTable pvtColLabel" colspan="1" rowspan="2">
                {{' ' + kolom + ' '}}
            </th>
            {% endfor %}
        </tr>
        <tr>
            <th class="pvtAxisLabel">{{ tabel.rij_naam.title() }}</th>
        </tr>
        </thead>
        <tbody>
        {% for rij in tabel.rijen %}
        <tr>
            <th class="pvtRowLabel" rowspan="1" colspan="2">
                {{ rij }} {{ tabel.geef_rij_omschrijving(rij) }}
            </th>
            {% for kolom in tabel.kolommen %}
            <td
                {% if tabel.is_grijze_cel(rij, kolom) %}
                    class="td grijzeCel"
                {% else %}
                    class="td witteCel"
                {% endif %}

                nowrap="true"
                {{ tabel.rij_naam }}="{{ rij }}"
                {{ tabel.kolom_naam }}="{{ kolom }}"

                {% if tabel.detail_weergave %}
                onclick="vul_detail(this, '{{ tabel.rij_naam }}', '{{ tabel.kolom_naam }}');"
                onkeydown="vul_detail(this, '{{ tabel.rij_naam }}', '{{ tabel.kolom_naam }}');"
                {% endif %}
            >
                {{ tabel[rij, kolom] }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>

    {% if tabel.detail_weergave %}
        <p>Klik een cel aan voor detail-informatie</p>
    {% else %}
        <p>Klik op een cel om deze te bewerken</p>
    {% endif %}
</div>

{% endmacro %}


{% macro controle_resultaat(resultaat) %}
<h4>Uitvoer van {{ resultaat.controle.omschrijving }}</h4>

{% if resultaat.is_geslaagd %}
<p class="success">De controle is geslaagd.</p>
{% else %}
<p class="error">De controle is onvoldoende. Zie onderstaande rapportage:</p>

<ol>
    {% for (opmerking, omschrijving) in resultaat.rapportage() %}
    <li title="{{ omschrijving }}">{{ opmerking }}</li>
    {% endfor %}
</ol>

{% endif %}

{% endmacro %}


{% macro record_toevoegen(draaitabel, data, bestandsnaam) %}

<form class="form-inline text-center muteerknoppen"
      role="form"
      method="post"
>
    <div class="form-group" style="padding-right: 50px;" naam="{{ draaitabel.rij_naam }}">
        <label for="rij">{{ draaitabel.rij_naam.title() }}:&nbsp; </label>
        <select class='form-control mutatie-invoer'
                style="width:100px;"
                name="{{ draaitabel.rij_naam }}">
            {% for code in draaitabel.geef_rij_keuzes() %}
            <option value="{{ code }}">
                {{ code }}: {{ draaitabel.geef_rij_omschrijving(code).title() }}
            </option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group" style="padding-right: 50px;" naam="{{ draaitabel.kolom_naam }}">
        <label for="kolom">{{ draaitabel.kolom_naam.title() }}:&nbsp; </label>
        <select class='form-control mutatie-invoer'
                style="width:100px;"
                name="{{ draaitabel.kolom_naam }}" >
            {% for code in draaitabel.geef_kolom_keuzes() %}
            <option value="{{ code }}">
                {{ code }}: {{ draaitabel.geef_kolom_omschrijving(code).title() }}
            </option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group" style="padding-right: 50px;" naam="{{ draaitabel.waarde_naam }}">
        <label for="bedrag">{{ draaitabel.waarde_naam.title() }}:&nbsp; </label>
        <input class="form-control mutatie-invoer"
               style="width:100px;"
               id="bedrag"
               type="number"
               name="bedrag"
               value="0"
        />
    </div>

    <input type="hidden"
           name="waarde_kant"
           value="{{ draaitabel.naam }}" />

    <input type="hidden"
           name="bestandsnaam"
           value='{{ bestandsnaam }}'/>

    <!-- TODO Onderstaande invoer is eigenlijk voor elke draaitabel hetzelfde -->
    <!-- Netter zou zijn om dit via een javascript functie op te halen. -->
    <input type="hidden"
           name="data"
           value='{{ data | tojson }}'/>

    <div class="form-group"><label style="width:100px;"></label></div>
    <button class="btn btn-primary" type="submit"
            title="Klik om mutatie te verwerken">
        Mutatie verwerken</button>
</form>

{% endmacro %}


{% macro bulkcorrecties_toevoegen(draaitabel, data, bestandsnaam, aantal_rijen) %}

{% set formulier_kolommen = ["Type", "Rij_soort", "Rij_code", "Kolom_soort", "Kolom_code"] %}
{% set formulier_kolommen = formulier_kolommen + ["Bedrag", "Omschrijving", "Reset"] %}

{% set type_opties = {"Type": ["lasten", "baten", "balans_lasten", "balans_baten", "balans_standen"]} %}

{% set rij_soort_opties = {} %}
{% set rij_code_opties = {} %}
{% set kolom_soort_opties = {} %}
{% set kolom_code_opties = {} %}

{# haal de opties op voor de form-controls #}
{# rij_soort, rij_code, kolom_soort, kolom_code #}

{% for item in type_opties["Type"] %}
    {% set foo = rij_soort_opties.update({item: [draaitabel[item].rij_naam.title().lower()]}) %}
    {% set bar = rij_code_opties.update({item: draaitabel[item].geef_rij_keuzes()}) %}
    {% set foo = kolom_soort_opties.update({item: [draaitabel[item].kolom_naam.title().lower()]}) %}
    {% set bar = kolom_code_opties.update({item: draaitabel[item].geef_kolom_keuzes()}) %}
{% endfor %}


<form class="form-inline text-center muteerknoppen"
      id="Form_bulkcorrecties"
      role="form"
      method="post"
>

    <div class="form-group" style="margin-bottom: 20px;float: center">
        <input class="form-control mutatie-invoer"
               readonly="readonly"
               style="color: blue;width: 600px;margin-right: 200px;text-align: center;"
               value="Voer hieronder de correcties in en klik op de knop 'Correcties verwerken'">

        <button class="btn btn-primary" style="margin-right: 20px;"
                type="button"
                title="Klik om correcties te verwerken"
                onclick="bulkcorrecties_verwerken();">
                Correcties verwerken
        </button>

        <button class="btn btn-primary" style="float: right"
                type="button"
                title="Klik om formulier leeg te maken"
                onclick="formulier_bulkcorrecties_leegmaken();">
                Formulier leegmaken
        </button>
    </div>

    {% for rij in range(aantal_rijen) %}

    <div style="margin-bottom: 4px" id="{{ 'bulkcorr_' + rij|string }}">

        {% for kolom in formulier_kolommen %}
        <div class="form-group" style="padding-right: 10px;">
            {% if rij == 0 %}
            <label class='form-control mutatie-invoer'
                   style="color: blue;display: block;margin-bottom: 10px;">{{ kolom }}</label>
            {% endif %}
            {% if kolom in ["Type", "Rij_soort", "Rij_code", "Kolom_soort", "Kolom_code"] %}
            <select class='form-control mutatie-invoer'
                    style="min-width: 150px;"
                    id="{{ kolom.lower() }}"
                    data-default-value="" >
                    <option disabled selected value="">...</option>
                    {% for code in type_opties[kolom] %}
                    <option value="{{ code }}">
                        {{ code }}
                    </option>
                    {% endfor %}
            </select>
            {% elif kolom == "Bedrag" %}
            <input class="form-control mutatie-invoer"
                   style="min-width: 150px;"
                   id="{{ kolom.lower() }}"
                   type="number"
                   value="0"
            />
            {% elif kolom == "Omschrijving" %}
            <input class="form-control mutatie-invoer"
                   style="min-width: 300px;"
                   id="{{ kolom.lower() }}"
                   type="text"
                   value="Bulkcorrectie Ocido"
            />
            {% elif kolom == "Reset" %}
            <button class="btn btn-primary"
                    style="float: right" type="button"
                    id="{{ kolom.lower() }}"
                    title="Klik om correctieregel leeg te maken" >
                    Wis regel
            </button>
            {% endif %}
        </div>
        {% endfor %}

    </div>

    {% endfor %}

    <input type="hidden"
           name="data"
           value='{{ data | tojson }}'/>
    <input type="hidden"
           name="bestandsnaam"
           value='{{ bestandsnaam }}'/>
    <input type="hidden"
           name="waarde_kant"
           value="bulkcorrecties"/>
    <input type="hidden"
           name="bulkcorrecties"
           value=""/>
    <input type="hidden"
           id="rij_soort_opties"
           value='{{ rij_soort_opties }}'/>
    <input type="hidden"
           id="rij_code_opties"
           value='{{ rij_code_opties }}'/>
    <input type="hidden"
           id="kolom_soort_opties"
           value='{{ kolom_soort_opties }}'/>
    <input type="hidden"
           id="kolom_code_opties"
           value='{{ kolom_code_opties }}'/>

</form>

{% endmacro %}